name: talent_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # State Management
  provider: ^6.1.1

  # HTTP & API
  dio: ^5.4.0
  
  # HTTP Server (for embedded backend)
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5

  # Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Form & Validation
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  
  # Image Picker
  image_picker: ^1.0.4
  file_picker: ^8.0.6
  
  # Date & Time
  intl: ^0.19.0
  
  # Utils
  url_launcher: ^6.2.1
  permission_handler: ^11.0.1

  # Google Sign In
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
